# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'MyCalculator.ui'
# Created by: PyQt5 UI code generator 5.10
# WARNING! All changes made in this file will be lost!
# Desc : View For My Calculator
# packages: PyQt5
# Author Ameya Salagre
# last changes : 4/5/2017


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):


    # Setting up the Ui in Form
    def setupUi(self, Form):
        
        #Initializing Form Object
        Form.setObjectName("Form")
        Form.resize(320, 461)
        Form.setMouseTracking(True)
        Form.setTabletTracking(True)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)

        #Intializing clear button
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(0, 110, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setMouseTracking(True)
        self.pushButton_clear.setTabletTracking(True)
        self.pushButton_clear.setAutoFillBackground(False)
        self.pushButton_clear.setStyleSheet("background-color: rgb(253, 112, 0)")
        self.pushButton_clear.setCheckable(False)
        self.pushButton_clear.setAutoDefault(False)
        self.pushButton_clear.setDefault(False)
        self.pushButton_clear.setFlat(False)
        self.pushButton_clear.setObjectName("pushButton_clear")

        #Initializing label Object
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setTabletTracking(True)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("background-color: rgba(204, 204, 204);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
      

        #Initialize divide(/) button
        self.pushButton_divide = QtWidgets.QPushButton(Form)
        self.pushButton_divide.setGeometry(QtCore.QRect(80, 110, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setMouseTracking(True)
        self.pushButton_divide.setTabletTracking(True)
        self.pushButton_divide.setAutoFillBackground(False)
        self.pushButton_divide.setStyleSheet("background-color: rgb(253, 112, 0)")
        self.pushButton_divide.setCheckable(False)
        self.pushButton_divide.setAutoDefault(False)
        self.pushButton_divide.setDefault(False)
        self.pushButton_divide.setFlat(False)
        self.pushButton_divide.setObjectName("pushButton_divide")
        

        #Initialize multiply(*) button
        self.pushButton_multiply = QtWidgets.QPushButton(Form)
        self.pushButton_multiply.setGeometry(QtCore.QRect(160, 110, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setMouseTracking(True)
        self.pushButton_multiply.setTabletTracking(True)
        self.pushButton_multiply.setAutoFillBackground(False)
        self.pushButton_multiply.setStyleSheet("background-color: rgb(253, 112, 0)")
        self.pushButton_multiply.setCheckable(False)
        self.pushButton_multiply.setAutoDefault(False)
        self.pushButton_multiply.setDefault(False)
        self.pushButton_multiply.setFlat(False)
        self.pushButton_multiply.setObjectName("pushButton_multiply")
       


        #Initialize backspace button
        self.pushButton_backspace = QtWidgets.QPushButton(Form)
        self.pushButton_backspace.setGeometry(QtCore.QRect(240, 110, 81, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_backspace.setFont(font)
        self.pushButton_backspace.setMouseTracking(True)
        self.pushButton_backspace.setTabletTracking(True)
        self.pushButton_backspace.setAutoFillBackground(False)
        self.pushButton_backspace.setStyleSheet("background-color: rgb(253, 112, 0)")
        self.pushButton_backspace.setCheckable(False)
        self.pushButton_backspace.setAutoDefault(False)
        self.pushButton_backspace.setDefault(False)
        self.pushButton_backspace.setFlat(False)
        self.pushButton_backspace.setObjectName("pushButton_backspace")
        

        #Initialize 9 button
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setMouseTracking(True)
        self.pushButton_9.setTabletTracking(True)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")


        #Initialize minus(-) button
        self.pushButton_minus = QtWidgets.QPushButton(Form)
        self.pushButton_minus.setGeometry(QtCore.QRect(240, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setMouseTracking(True)
        self.pushButton_minus.setTabletTracking(True)
        self.pushButton_minus.setAutoFillBackground(False)
        self.pushButton_minus.setStyleSheet("background-color: rgb(253, 112, 0)")
        self.pushButton_minus.setCheckable(False)
        self.pushButton_minus.setAutoDefault(False)
        self.pushButton_minus.setDefault(False)
        self.pushButton_minus.setFlat(False)
        self.pushButton_minus.setObjectName("pushButton_minus")

        #Initialize 8 button
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setMouseTracking(True)
        self.pushButton_8.setTabletTracking(True)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")


        #Initialize 7 button
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setMouseTracking(True)
        self.pushButton_7.setTabletTracking(True)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")

        #Initialize 6 button
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setMouseTracking(True)
        self.pushButton_6.setTabletTracking(True)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")

        #Initialize plus(+) button
        self.pushButton_plus = QtWidgets.QPushButton(Form)
        self.pushButton_plus.setGeometry(QtCore.QRect(240, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setMouseTracking(True)
        self.pushButton_plus.setTabletTracking(True)
        self.pushButton_plus.setAutoFillBackground(False)
        self.pushButton_plus.setStyleSheet("background-color: rgb(253, 112, 0)")
        self.pushButton_plus.setCheckable(False)
        self.pushButton_plus.setAutoDefault(False)
        self.pushButton_plus.setDefault(False)
        self.pushButton_plus.setFlat(False)
        self.pushButton_plus.setObjectName("pushButton_plus")

        #Initialize 5 button
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setMouseTracking(True)
        self.pushButton_5.setTabletTracking(True)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")

        #Initialize 4 button    
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setMouseTracking(True)
        self.pushButton_4.setTabletTracking(True)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")


        #Initialize 3 button
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 320, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setMouseTracking(True)
        self.pushButton_3.setTabletTracking(True)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")


        #Initialize 2 button
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 320, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setTabletTracking(True)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")

        #Initialize 1 button
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 320, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setMouseTracking(True)
        self.pushButton_1.setTabletTracking(True)
        self.pushButton_1.setAutoFillBackground(False)
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")

        #Initialize decimal button
        self.pushButton_decimal = QtWidgets.QPushButton(Form)
        self.pushButton_decimal.setGeometry(QtCore.QRect(160, 390, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_decimal.setFont(font)
        self.pushButton_decimal.setMouseTracking(True)
        self.pushButton_decimal.setTabletTracking(True)
        self.pushButton_decimal.setAutoFillBackground(False)
        self.pushButton_decimal.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_decimal.setCheckable(False)
        self.pushButton_decimal.setAutoDefault(False)
        self.pushButton_decimal.setDefault(False)
        self.pushButton_decimal.setFlat(False)
        self.pushButton_decimal.setObjectName("pushButton_decimal")

        #Initialize equal button
        self.pushButton_equal = QtWidgets.QPushButton(Form)
        self.pushButton_equal.setGeometry(QtCore.QRect(240, 320, 81, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setMouseTracking(True)
        self.pushButton_equal.setTabletTracking(True)
        self.pushButton_equal.setAutoFillBackground(False)
        self.pushButton_equal.setStyleSheet("background-color: rgb(65, 205, 82)")
        self.pushButton_equal.setCheckable(False)
        self.pushButton_equal.setAutoDefault(False)
        self.pushButton_equal.setDefault(False)
        self.pushButton_equal.setFlat(False)
        self.pushButton_equal.setObjectName("pushButton_equal")
        
        #Initialize 0 button     
        self.pushButton_0 = QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 390, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setMouseTracking(True)
        self.pushButton_0.setTabletTracking(True)
        self.pushButton_0.setAutoFillBackground(False)
        self.pushButton_0.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pushButton_0.setCheckable(False)
        self.pushButton_0.setAutoDefault(False)
        self.pushButton_0.setDefault(False)
        self.pushButton_0.setFlat(False)
        self.pushButton_0.setObjectName("pushButton_0")

        # assigning Functions on each
        self.pushButton_clear.raise_()
        self.pushButton_divide.raise_()
        self.pushButton_multiply.raise_()
        self.pushButton_backspace.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_minus.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_plus.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_0.raise_()
        self.pushButton_decimal.raise_()
        self.pushButton_equal.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    # Re Translate UI Components
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.pushButton_clear.setText(_translate("Form", "C"))
        self.pushButton_divide.setText(_translate("Form", "/"))
        self.pushButton_multiply.setText(_translate("Form", "x"))
        self.pushButton_backspace.setText(_translate("Form", "\u232b"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_decimal.setText(_translate("Form", "."))
        self.pushButton_equal.setText(_translate("Form", "="))
        self.pushButton_0.setText(_translate("Form", "0"))

